name: Run Tests on Merge to Develop

on:
  push:
    branches:
      - develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: 3.11.9

      - name: Install dependencies
        run: python -m pip install --upgrade pip 
             pip install -r requirements.txt

      - name: Run tests with pytest
        run: pytest

